name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  workspace:
    description: git local working directory
    required: true
  config-server-url:  # id of input
    description: 'remote configuration server'
    required: true
    default: 'http://localhost:8888/configuration-service/1.0.0/properties'
  entity-id:
    description: 'service provider'
    required: true
    default: 'ADB'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.mjs'
